# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('author', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('link', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('small_image', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('image_link', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('video', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
